# Generated by Django 6.1 on 2026-09-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysis_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='missing_skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
