# Generated by Django 6.1.1 on 2026-10-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysis_missing_skills'),
        ('documents', '0004_remove_joboffer_skills_delete_skill_joboffer_skills'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.UniqueConstraint(fields=('cv', 'job_offer'), name='unique_cv_job_offer'),
        ),
    ]
