# Generated by Django 6.1.1 on 2026-10-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysis_unique_cv_job_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
