# Generated by Django 6.1.1 on 2026-10-02 09:29

from django.db import migrations, models


def fix_invalid_missing_skills(apps, schema_editor):
    """Set missing_skills to [] for any rows with NULL or invalid JSON."""
    Analysis = apps.get_model('analysis', 'Analysis')
    db_alias = schema_editor.connection.alias
    Analysis.objects.using(db_alias).filter(
        missing_skills__isnull=True
    ).update(missing_skills=[])


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysis_unique_cv_job_offer'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_missing_skills, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='analysis',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
