# Generated by Django 6.1.1 on 2026-10-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysis_missing_skills'),
        ('documents', '0004_remove_joboffer_skills_delete_skill_joboffer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.cv'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.joboffer'),
        ),
    ]
