# Generated by Django 6.1 on 2026-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_department',
            field=models.CharField(choices=[('it', 'IT'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'HR'), ('finance', 'Finance'), ('operations', 'Operations'), ('customer_support', 'Customer Support'), ('legal', 'Legal'), ('product', 'Product'), ('design', 'Design')], default='it', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='department',
            field=models.CharField(choices=[('it', 'IT'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'HR'), ('finance', 'Finance'), ('operations', 'Operations'), ('customer_support', 'Customer Support'), ('legal', 'Legal'), ('product', 'Product'), ('design', 'Design')], default='it', max_length=30),
        ),
    ]
