# Generated by Django 6.1 on 2026-09-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_skill_joboffer_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
